version: 2.1

orbs:
  node: circleci/node@5.1.0
  ruby: circleci/ruby@2.0.0

executors:
  test-executor:
    docker:
      - image: cimg/ruby:3.2.2
      - image: cimg/node:16.20-browsers
      - image: mcr.microsoft.com/playwright:v1.20.0-focal
      - image: cimg/postgres:14.6
        environment:
          POSTGRES_USER: st2
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: st2
      PGPASSWORD: ""
      PLATFORM_FEE_PERCENT: "0.15"
      REACT_APP_API_URL: http://localhost:8080/
      REACT_APP_CALL_END_WARNING: http://localhost:8080/call-end-warning.mp3
      REACT_APP_TEN_MIN_WARNING: http://localhost:8080/ten-min-warning.mp3
      REACT_APP_TWENTY_MIN_WARNING: http://localhost:8080/twenty-min-warning.mp3
      REACT_APP_VERSION: $npm_package_version
      REACT_APP_NAME: $npm_package_name
      E2E_TESTING: true
      DESKTOP_APP_VERION: 1.0.0
      SYSTEM_ACCESS_KEY: system-access-key
      REACT_APP_SYSTEM_ACCESS_KEY: system-access-key
      DEBUG: pw:browser*

commands:
  prepare-for-testing:
      steps:
          - run:
              name: Clone backend repository
              command: git clone --single-branch --branch 'issue#initial_data_for_e2e_testing' https://$GIT_ACCESS_TOKEN@github.com/makersource/mks-st2.git ~/backend
          - restore_cache:
              keys:
                - &gem-cache gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "~/backend/Gemfile.lock" }}
                - gem-cache-v1-{{ arch }}-{{ .Branch }}
                - gem-cache-v1
          - run:
              name: Run Backend install
              command: |
                cd ~/backend
                bundle install --path vendor/bundle
          - save_cache:
              key: *gem-cache
              paths:
                - ~/backend/vendor/bundle
          - run:
              name: Install ImageMagick
              command: sudo apt-get update --allow-releaseinfo-change && sudo apt-get install -y imagemagick
          - run:
              name: Install Redis
              command: sudo apt-get install -y redis-server && redis-server --daemonize yes
          - run:
              name: Wait for DB
              command: dockerize -wait tcp://localhost:5432 -timeout 1m
          - run:
              name: Wait for Redis
              command: dockerize -wait tcp://localhost:6379 -timeout 1m
          - run:
              name: Run Backend Server
              command: |
                cd ~/backend
                bundle exec rails db:create db:schema:load
                bundle exec rails mockup_data:e2e_testing
                bundle exec rails s -u puma -d -p 8080
          - run:
              name: Wait for backend
              command: dockerize -wait localhost:8080 -timeout 1m
jobs:
  test:
    executor: test-executor
    steps:
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - prepare-for-testing
      - checkout
      - node/install-packages:
          override-ci-command: yarn install
      - run: yarn lint
      - run: npx playwright install --with-deps chromium
      - run: yarn electron-pack:linux --dir
      - run: sudo apt install libgtk-3-0
      - run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" -- npx playwright test

workflows:
  version: 2

  test-only:
    jobs:
      - test
